language: python
sudo: required
dist: xenial
before_install:
    - |
      if [[ $PYTHON && "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install openssl readline;
        brew outdated pyenv || brew upgrade pyenv;
        brew install pyenv-virtualenv;
        pyenv install $PYTHON;
        export PYENV_VERSION=$PYTHON;
        export PATH="/Users/travis/.pyenv/shims:${PATH}";
        pyenv-virtualenv venv;
        source venv/bin/activate;
        python --version;
      fi;
install:
    - pip install -r developer_requirements.txt
script:
    - ./run-tests.sh
    - codecov
after_success:
    - if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "osx" ]]; then
      FASTAVRO_USE_CYTHON=1 python setup.py bdist_wheel;
      fi;
    - if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "linux" && $TRAVIS_PYTHON_VERSION != *"pypy"* ]]; then
      docker run --rm -v "$(pwd):/data" quay.io/pypa/manylinux1_x86_64 bash -c "/data/.travis_build_wheel.sh $TRAVIS_PYTHON_VERSION";
      fi;
deploy:
    provider: releases
    api_key:
        secure: "DqDkKBKw20riyr1WeRZtMEUlmD9cCJNf/JJD5res8HSx8wUz+rI1aDpk0wCaehdLS2zsvUpf027EHfkseUZaMr3wMfwHQ9FxSEOZ04K8Wmxqk60bzEHwqL6xBe7M3K3RxYUKH6oZDekN2I0imkllHA4v6iG0JGmoacNAos60NdA="
    file_glob: true
    file: 'dist/fastavro-*.whl'
    skip_cleanup: true
    on:
        tags: true
        condition: $TRAVIS_PYTHON_VERSION != *"pypy"*

matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - python: 3.7
        - dist: trusty
          python: pypy
        - dist: trusty
          python: pypy3
        - os: osx
          language: generic
          env:
            - PYTHON='2.7.15'
        - os: osx
          language: generic
          env:
            - PYTHON='3.4.8'
        - os: osx
          language: generic
          env:
            - PYTHON='3.5.5'
        - os: osx
          language: generic
          env:
            - PYTHON='3.6.6'
        - os: osx
          language: generic
          env:
            - PYTHON='3.7.0'
